"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/execle.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks")

# gl_FUNC_EXECLE: the only decision is made on $host_os.
#   case "$host_os" in
#     mingw* | windows*) REPLACE_EXECLE=1 ;;
#   esac
autoconf(
    name = "gl_FUNC_EXECLE",
    checks = select({
        "@platforms//os:windows": [
            checks.AC_SUBST("REPLACE_EXECLE", 1),
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//autoconf/macros/AC_CANONICAL_HOST",  # AC_REQUIRE([AC_CANONICAL_HOST]),
    ],
)

autoconf(
    name = "execle",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_FUNC_EXECLE",
    ],
)
