#!/usr/bin/env bash

bazel test -- //gnulib/tests/compatibility/cbrt/... \
    //gnulib/tests/compatibility/chown/... \
    //gnulib/tests/compatibility/ctype_h/... \
    //gnulib/tests/compatibility/d-ino/... \
    //gnulib/tests/compatibility/d-type/... \
    //gnulib/tests/compatibility/double-slash-root/... \
    //gnulib/tests/compatibility/errno_h/... \
    //gnulib/tests/compatibility/exp2/... \
    //gnulib/tests/compatibility/expm1/... \
    //gnulib/tests/compatibility/fabsf/... \
    //gnulib/tests/compatibility/fabsl/... \
    //gnulib/tests/compatibility/fchdir/... \
    //gnulib/tests/compatibility/fflush/... \
    //gnulib/tests/compatibility/floor/... \
    //gnulib/tests/compatibility/fmod/... \
    //gnulib/tests/compatibility/fnmatch_h/... \
    //gnulib/tests/compatibility/frexpf/... \
    //gnulib/tests/compatibility/getgroups/... \
    //gnulib/tests/compatibility/glob_h/... \
    //gnulib/tests/compatibility/hostent/... \
    //gnulib/tests/compatibility/hypot/... \
    //gnulib/tests/compatibility/iconv_h/... \
    //gnulib/tests/compatibility/inet_ntop/... \
    //gnulib/tests/compatibility/inline/... \
    //gnulib/tests/compatibility/isnanf/... \
    //gnulib/tests/compatibility/langinfo_h/... \
    //gnulib/tests/compatibility/ldexpf/... \
    //gnulib/tests/compatibility/link/... \
    //gnulib/tests/compatibility/locale_h/... \
    //gnulib/tests/compatibility/log1pf/... \
    //gnulib/tests/compatibility/log1pl/... \
    //gnulib/tests/compatibility/logp1/... \
    //gnulib/tests/compatibility/malloc_h/... \
    //gnulib/tests/compatibility/mbrtowc/... \
    //gnulib/tests/compatibility/memchr/... \
    //gnulib/tests/compatibility/mkfifo/... \
    //gnulib/tests/compatibility/mktime/... \
    //gnulib/tests/compatibility/msvc-inval/... \
    //gnulib/tests/compatibility/open-slash/... \
    //gnulib/tests/compatibility/openat/... \
    //gnulib/tests/compatibility/printf/... \
    //gnulib/tests/compatibility/pthread_h/... \
    //gnulib/tests/compatibility/rename/... \
    //gnulib/tests/compatibility/servent/... \
    //gnulib/tests/compatibility/signal_h/... \
    //gnulib/tests/compatibility/sockets/... \
    //gnulib/tests/compatibility/spawn_h/... \
    //gnulib/tests/compatibility/sqrtl/... \
    //gnulib/tests/compatibility/sys_ioctl_h/... \
    //gnulib/tests/compatibility/sys_stat_h/... \
    //gnulib/tests/compatibility/sys_types_h/... \
    //gnulib/tests/compatibility/systemd/... \
    //gnulib/tests/compatibility/truncl/... \
    //gnulib/tests/compatibility/uchar_h/... \
    //gnulib/tests/compatibility/ungetc/... \
    //gnulib/tests/compatibility/unlocked-io/... \
    //gnulib/tests/compatibility/vasnprintf/... \
    //gnulib/tests/compatibility/wctype_h/...
