#!/usr/bin/env bash
git mv gnulib/tests/compatibility/accept4/golden_config.h.in gnulib/tests/compatibility/accept4/golden_config_macos.h.in
git mv gnulib/tests/compatibility/access/golden_config.h.in gnulib/tests/compatibility/access/golden_config_macos.h.in
git mv gnulib/tests/compatibility/acl/golden_config.h.in gnulib/tests/compatibility/acl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/argp/golden_config.h.in gnulib/tests/compatibility/argp/golden_config_macos.h.in
git mv gnulib/tests/compatibility/arpa_inet_h/golden_config.h.in gnulib/tests/compatibility/arpa_inet_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/c32rtomb/golden_config.h.in gnulib/tests/compatibility/c32rtomb/golden_config_macos.h.in
git mv gnulib/tests/compatibility/call_once/golden_config.h.in gnulib/tests/compatibility/call_once/golden_config_macos.h.in
git mv gnulib/tests/compatibility/canonicalize/golden_config.h.in gnulib/tests/compatibility/canonicalize/golden_config_macos.h.in
git mv gnulib/tests/compatibility/cbrtl/golden_config.h.in gnulib/tests/compatibility/cbrtl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/chown/golden_config.h.in gnulib/tests/compatibility/chown/golden_config_macos.h.in
git mv gnulib/tests/compatibility/cnd/golden_config.h.in gnulib/tests/compatibility/cnd/golden_config_macos.h.in
git mv gnulib/tests/compatibility/copysignl/golden_config.h.in gnulib/tests/compatibility/copysignl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/dup3/golden_config.h.in gnulib/tests/compatibility/dup3/golden_config_macos.h.in
git mv gnulib/tests/compatibility/duplocale/golden_config.h.in gnulib/tests/compatibility/duplocale/golden_config_macos.h.in
git mv gnulib/tests/compatibility/endian_h/golden_config.h.in gnulib/tests/compatibility/endian_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/error_h/golden_config.h.in gnulib/tests/compatibility/error_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/euidaccess/golden_config.h.in gnulib/tests/compatibility/euidaccess/golden_config_macos.h.in
git mv gnulib/tests/compatibility/exp2l/golden_config.h.in gnulib/tests/compatibility/exp2l/golden_config_macos.h.in
git mv gnulib/tests/compatibility/explicit_bzero/golden_config.h.in gnulib/tests/compatibility/explicit_bzero/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fabsl/golden_config.h.in gnulib/tests/compatibility/fabsl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fchownat/golden_config.h.in gnulib/tests/compatibility/fchownat/golden_config_macos.h.in
git mv gnulib/tests/compatibility/filemode/golden_config.h.in gnulib/tests/compatibility/filemode/golden_config_macos.h.in
git mv gnulib/tests/compatibility/floorl/golden_config.h.in gnulib/tests/compatibility/floorl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fmodl/golden_config.h.in gnulib/tests/compatibility/fmodl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fnmatch/golden_config.h.in gnulib/tests/compatibility/fnmatch/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fprintf-posix/golden_config.h.in gnulib/tests/compatibility/fprintf-posix/golden_config_macos.h.in
git mv gnulib/tests/compatibility/fpurge/golden_config.h.in gnulib/tests/compatibility/fpurge/golden_config_macos.h.in
git mv gnulib/tests/compatibility/frexpl/golden_config.h.in gnulib/tests/compatibility/frexpl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/getprogname/golden_config.h.in gnulib/tests/compatibility/getprogname/golden_config_macos.h.in
git mv gnulib/tests/compatibility/glob/golden_config.h.in gnulib/tests/compatibility/glob/golden_config_macos.h.in
git mv gnulib/tests/compatibility/hypotl/golden_config.h.in gnulib/tests/compatibility/hypotl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/isfinite/golden_config.h.in gnulib/tests/compatibility/isfinite/golden_config_macos.h.in
git mv gnulib/tests/compatibility/isinf/golden_config.h.in gnulib/tests/compatibility/isinf/golden_config_macos.h.in
git mv gnulib/tests/compatibility/isnanl/golden_config.h.in gnulib/tests/compatibility/isnanl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/lchown/golden_config.h.in gnulib/tests/compatibility/lchown/golden_config_macos.h.in
git mv gnulib/tests/compatibility/ldexpl/golden_config.h.in gnulib/tests/compatibility/ldexpl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/locale_h/golden_config.h.in gnulib/tests/compatibility/locale_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/log1pl/golden_config.h.in gnulib/tests/compatibility/log1pl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/logp1l/golden_config.h.in gnulib/tests/compatibility/logp1l/golden_config_macos.h.in
git mv gnulib/tests/compatibility/mbrtoc16/golden_config.h.in gnulib/tests/compatibility/mbrtoc16/golden_config_macos.h.in
git mv gnulib/tests/compatibility/mbrtoc32/golden_config.h.in gnulib/tests/compatibility/mbrtoc32/golden_config_macos.h.in
git mv gnulib/tests/compatibility/mempcpy/golden_config.h.in gnulib/tests/compatibility/mempcpy/golden_config_macos.h.in
git mv gnulib/tests/compatibility/memrchr/golden_config.h.in gnulib/tests/compatibility/memrchr/golden_config_macos.h.in
git mv gnulib/tests/compatibility/mkfifoat/golden_config.h.in gnulib/tests/compatibility/mkfifoat/golden_config_macos.h.in
git mv gnulib/tests/compatibility/monetary_h/golden_config.h.in gnulib/tests/compatibility/monetary_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/newlocale/golden_config.h.in gnulib/tests/compatibility/newlocale/golden_config_macos.h.in
git mv gnulib/tests/compatibility/nproc/golden_config.h.in gnulib/tests/compatibility/nproc/golden_config_macos.h.in
git mv gnulib/tests/compatibility/open/golden_config.h.in gnulib/tests/compatibility/open/golden_config_macos.h.in
git mv gnulib/tests/compatibility/openat/golden_config.h.in gnulib/tests/compatibility/openat/golden_config_macos.h.in
git mv gnulib/tests/compatibility/physmem/golden_config.h.in gnulib/tests/compatibility/physmem/golden_config_macos.h.in
git mv gnulib/tests/compatibility/pipe2/golden_config.h.in gnulib/tests/compatibility/pipe2/golden_config_macos.h.in
git mv gnulib/tests/compatibility/posix_spawn/golden_config.h.in gnulib/tests/compatibility/posix_spawn/golden_config_macos.h.in
git mv gnulib/tests/compatibility/pty_h/golden_config.h.in gnulib/tests/compatibility/pty_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/random_r/golden_config.h.in gnulib/tests/compatibility/random_r/golden_config_macos.h.in
git mv gnulib/tests/compatibility/rawmemchr/golden_config.h.in gnulib/tests/compatibility/rawmemchr/golden_config_macos.h.in
git mv gnulib/tests/compatibility/readutmp/golden_config.h.in gnulib/tests/compatibility/readutmp/golden_config_macos.h.in
git mv gnulib/tests/compatibility/reallocarray/golden_config.h.in gnulib/tests/compatibility/reallocarray/golden_config_macos.h.in
git mv gnulib/tests/compatibility/renameat/golden_config.h.in gnulib/tests/compatibility/renameat/golden_config_macos.h.in
git mv gnulib/tests/compatibility/secure_getenv/golden_config.h.in gnulib/tests/compatibility/secure_getenv/golden_config_macos.h.in
git mv gnulib/tests/compatibility/sethostname/golden_config.h.in gnulib/tests/compatibility/sethostname/golden_config_macos.h.in
git mv gnulib/tests/compatibility/sigabbrev_np/golden_config.h.in gnulib/tests/compatibility/sigabbrev_np/golden_config_macos.h.in
git mv gnulib/tests/compatibility/sigaction/golden_config.h.in gnulib/tests/compatibility/sigaction/golden_config_macos.h.in
git mv gnulib/tests/compatibility/sigdescr_np/golden_config.h.in gnulib/tests/compatibility/sigdescr_np/golden_config_macos.h.in
git mv gnulib/tests/compatibility/stat/golden_config.h.in gnulib/tests/compatibility/stat/golden_config_macos.h.in
git mv gnulib/tests/compatibility/strchrnul/golden_config.h.in gnulib/tests/compatibility/strchrnul/golden_config_macos.h.in
git mv gnulib/tests/compatibility/strerror/golden_config.h.in gnulib/tests/compatibility/strerror/golden_config_macos.h.in
git mv gnulib/tests/compatibility/strerror_r/golden_config.h.in gnulib/tests/compatibility/strerror_r/golden_config_macos.h.in
git mv gnulib/tests/compatibility/strsignal/golden_config.h.in gnulib/tests/compatibility/strsignal/golden_config_macos.h.in
git mv gnulib/tests/compatibility/strverscmp/golden_config.h.in gnulib/tests/compatibility/strverscmp/golden_config_macos.h.in
git mv gnulib/tests/compatibility/thrd/golden_config.h.in gnulib/tests/compatibility/thrd/golden_config_macos.h.in
git mv gnulib/tests/compatibility/truncl/golden_config.h.in gnulib/tests/compatibility/truncl/golden_config_macos.h.in
git mv gnulib/tests/compatibility/uchar_h/golden_config.h.in gnulib/tests/compatibility/uchar_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/unlockpt/golden_config.h.in gnulib/tests/compatibility/unlockpt/golden_config_macos.h.in
git mv gnulib/tests/compatibility/vfprintf-posix/golden_config.h.in gnulib/tests/compatibility/vfprintf-posix/golden_config_macos.h.in
git mv gnulib/tests/compatibility/wchar_h/golden_config.h.in gnulib/tests/compatibility/wchar_h/golden_config_macos.h.in
git mv gnulib/tests/compatibility/wmempcpy/golden_config.h.in gnulib/tests/compatibility/wmempcpy/golden_config_macos.h.in
git mv gnulib/tests/compatibility/accept4/golden_subst.h.in gnulib/tests/compatibility/accept4/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/access/golden_subst.h.in gnulib/tests/compatibility/access/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/acl/golden_subst.h.in gnulib/tests/compatibility/acl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/acos/golden_subst.h.in gnulib/tests/compatibility/acos/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/acosf/golden_subst.h.in gnulib/tests/compatibility/acosf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/aligned_alloc/golden_subst.h.in gnulib/tests/compatibility/aligned_alloc/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/arpa_inet_h/golden_subst.h.in gnulib/tests/compatibility/arpa_inet_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/asin/golden_subst.h.in gnulib/tests/compatibility/asin/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/asinf/golden_subst.h.in gnulib/tests/compatibility/asinf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/assert_h/golden_subst.h.in gnulib/tests/compatibility/assert_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/atan/golden_subst.h.in gnulib/tests/compatibility/atan/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/atan2/golden_subst.h.in gnulib/tests/compatibility/atan2/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/atan2f/golden_subst.h.in gnulib/tests/compatibility/atan2f/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/atanf/golden_subst.h.in gnulib/tests/compatibility/atanf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/btowc/golden_subst.h.in gnulib/tests/compatibility/btowc/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/c32rtomb/golden_subst.h.in gnulib/tests/compatibility/c32rtomb/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/call_once/golden_subst.h.in gnulib/tests/compatibility/call_once/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/canonicalize/golden_subst.h.in gnulib/tests/compatibility/canonicalize/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cbrt/golden_subst.h.in gnulib/tests/compatibility/cbrt/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cbrtf/golden_subst.h.in gnulib/tests/compatibility/cbrtf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cbrtl/golden_subst.h.in gnulib/tests/compatibility/cbrtl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/ceil/golden_subst.h.in gnulib/tests/compatibility/ceil/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/ceilf/golden_subst.h.in gnulib/tests/compatibility/ceilf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/chown/golden_subst.h.in gnulib/tests/compatibility/chown/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cnd/golden_subst.h.in gnulib/tests/compatibility/cnd/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/copysignl/golden_subst.h.in gnulib/tests/compatibility/copysignl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cos/golden_subst.h.in gnulib/tests/compatibility/cos/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/cosf/golden_subst.h.in gnulib/tests/compatibility/cosf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/coshf/golden_subst.h.in gnulib/tests/compatibility/coshf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/dup3/golden_subst.h.in gnulib/tests/compatibility/dup3/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/duplocale/golden_subst.h.in gnulib/tests/compatibility/duplocale/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/endian_h/golden_subst.h.in gnulib/tests/compatibility/endian_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/error_h/golden_subst.h.in gnulib/tests/compatibility/error_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/euidaccess/golden_subst.h.in gnulib/tests/compatibility/euidaccess/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/exp2f/golden_subst.h.in gnulib/tests/compatibility/exp2f/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/exp2l/golden_subst.h.in gnulib/tests/compatibility/exp2l/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/expf/golden_subst.h.in gnulib/tests/compatibility/expf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/explicit_bzero/golden_subst.h.in gnulib/tests/compatibility/explicit_bzero/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/expm1f/golden_subst.h.in gnulib/tests/compatibility/expm1f/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fabs/golden_subst.h.in gnulib/tests/compatibility/fabs/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fabsf/golden_subst.h.in gnulib/tests/compatibility/fabsf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fabsl/golden_subst.h.in gnulib/tests/compatibility/fabsl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/faccessat/golden_subst.h.in gnulib/tests/compatibility/faccessat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fchownat/golden_subst.h.in gnulib/tests/compatibility/fchownat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/floorf/golden_subst.h.in gnulib/tests/compatibility/floorf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/floorl/golden_subst.h.in gnulib/tests/compatibility/floorl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fmodf/golden_subst.h.in gnulib/tests/compatibility/fmodf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fmodl/golden_subst.h.in gnulib/tests/compatibility/fmodl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fnmatch/golden_subst.h.in gnulib/tests/compatibility/fnmatch/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fprintf-posix/golden_subst.h.in gnulib/tests/compatibility/fprintf-posix/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fpurge/golden_subst.h.in gnulib/tests/compatibility/fpurge/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/free/golden_subst.h.in gnulib/tests/compatibility/free/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/frexpl/golden_subst.h.in gnulib/tests/compatibility/frexpl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/fseeko/golden_subst.h.in gnulib/tests/compatibility/fseeko/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/ftello/golden_subst.h.in gnulib/tests/compatibility/ftello/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/futimens/golden_subst.h.in gnulib/tests/compatibility/futimens/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/getline/golden_subst.h.in gnulib/tests/compatibility/getline/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/getprogname/golden_subst.h.in gnulib/tests/compatibility/getprogname/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/glob/golden_subst.h.in gnulib/tests/compatibility/glob/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/group-member/golden_subst.h.in gnulib/tests/compatibility/group-member/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/hypotf/golden_subst.h.in gnulib/tests/compatibility/hypotf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/hypotl/golden_subst.h.in gnulib/tests/compatibility/hypotl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/isfinite/golden_subst.h.in gnulib/tests/compatibility/isfinite/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/isinf/golden_subst.h.in gnulib/tests/compatibility/isinf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/isnanl/golden_subst.h.in gnulib/tests/compatibility/isnanl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/langinfo_h/golden_subst.h.in gnulib/tests/compatibility/langinfo_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/lchown/golden_subst.h.in gnulib/tests/compatibility/lchown/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/ldexpl/golden_subst.h.in gnulib/tests/compatibility/ldexpl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/locale_h/golden_subst.h.in gnulib/tests/compatibility/locale_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/log10f/golden_subst.h.in gnulib/tests/compatibility/log10f/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/log1p/golden_subst.h.in gnulib/tests/compatibility/log1p/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/log1pf/golden_subst.h.in gnulib/tests/compatibility/log1pf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/log1pl/golden_subst.h.in gnulib/tests/compatibility/log1pl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logb/golden_subst.h.in gnulib/tests/compatibility/logb/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logbf/golden_subst.h.in gnulib/tests/compatibility/logbf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logf/golden_subst.h.in gnulib/tests/compatibility/logf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logp1/golden_subst.h.in gnulib/tests/compatibility/logp1/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logp1f/golden_subst.h.in gnulib/tests/compatibility/logp1f/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/logp1l/golden_subst.h.in gnulib/tests/compatibility/logp1l/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/lstat/golden_subst.h.in gnulib/tests/compatibility/lstat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbrlen/golden_subst.h.in gnulib/tests/compatibility/mbrlen/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbrtoc16/golden_subst.h.in gnulib/tests/compatibility/mbrtoc16/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbrtoc32/golden_subst.h.in gnulib/tests/compatibility/mbrtoc32/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbrtowc/golden_subst.h.in gnulib/tests/compatibility/mbrtowc/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbsinit/golden_subst.h.in gnulib/tests/compatibility/mbsinit/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mbsrtowcs/golden_subst.h.in gnulib/tests/compatibility/mbsrtowcs/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/memmem/golden_subst.h.in gnulib/tests/compatibility/memmem/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mempcpy/golden_subst.h.in gnulib/tests/compatibility/mempcpy/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/memrchr/golden_subst.h.in gnulib/tests/compatibility/memrchr/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mkfifoat/golden_subst.h.in gnulib/tests/compatibility/mkfifoat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/mntent_h/golden_subst.h.in gnulib/tests/compatibility/mntent_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/monetary_h/golden_subst.h.in gnulib/tests/compatibility/monetary_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/newlocale/golden_subst.h.in gnulib/tests/compatibility/newlocale/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/obstack/golden_subst.h.in gnulib/tests/compatibility/obstack/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/off64_t/golden_subst.h.in gnulib/tests/compatibility/off64_t/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/openat/golden_subst.h.in gnulib/tests/compatibility/openat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/pipe2/golden_subst.h.in gnulib/tests/compatibility/pipe2/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/posix_spawn/golden_subst.h.in gnulib/tests/compatibility/posix_spawn/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/powf/golden_subst.h.in gnulib/tests/compatibility/powf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/pthread_mutex_timedlock/golden_subst.h.in gnulib/tests/compatibility/pthread_mutex_timedlock/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/pty_h/golden_subst.h.in gnulib/tests/compatibility/pty_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/random_r/golden_subst.h.in gnulib/tests/compatibility/random_r/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/rawmemchr/golden_subst.h.in gnulib/tests/compatibility/rawmemchr/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/reallocarray/golden_subst.h.in gnulib/tests/compatibility/reallocarray/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/renameat/golden_subst.h.in gnulib/tests/compatibility/renameat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/rintf/golden_subst.h.in gnulib/tests/compatibility/rintf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sched_yield/golden_subst.h.in gnulib/tests/compatibility/sched_yield/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/secure_getenv/golden_subst.h.in gnulib/tests/compatibility/secure_getenv/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/semaphore/golden_subst.h.in gnulib/tests/compatibility/semaphore/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/setenv/golden_subst.h.in gnulib/tests/compatibility/setenv/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sigabbrev_np/golden_subst.h.in gnulib/tests/compatibility/sigabbrev_np/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sigdescr_np/golden_subst.h.in gnulib/tests/compatibility/sigdescr_np/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/signal_h/golden_subst.h.in gnulib/tests/compatibility/signal_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sinf/golden_subst.h.in gnulib/tests/compatibility/sinf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sinhf/golden_subst.h.in gnulib/tests/compatibility/sinhf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sqrtf/golden_subst.h.in gnulib/tests/compatibility/sqrtf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/stat/golden_subst.h.in gnulib/tests/compatibility/stat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/stdlib_h/golden_subst.h.in gnulib/tests/compatibility/stdlib_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/strcasestr/golden_subst.h.in gnulib/tests/compatibility/strcasestr/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/strchrnul/golden_subst.h.in gnulib/tests/compatibility/strchrnul/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/strerror/golden_subst.h.in gnulib/tests/compatibility/strerror/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/strverscmp/golden_subst.h.in gnulib/tests/compatibility/strverscmp/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/symlink/golden_subst.h.in gnulib/tests/compatibility/symlink/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/symlinkat/golden_subst.h.in gnulib/tests/compatibility/symlinkat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sys_cdefs_h/golden_subst.h.in gnulib/tests/compatibility/sys_cdefs_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/sys_types_h/golden_subst.h.in gnulib/tests/compatibility/sys_types_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/tanf/golden_subst.h.in gnulib/tests/compatibility/tanf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/tanhf/golden_subst.h.in gnulib/tests/compatibility/tanhf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/thrd/golden_subst.h.in gnulib/tests/compatibility/thrd/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/thread/golden_subst.h.in gnulib/tests/compatibility/thread/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/threadlib/golden_subst.h.in gnulib/tests/compatibility/threadlib/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/timegm/golden_subst.h.in gnulib/tests/compatibility/timegm/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/trunc/golden_subst.h.in gnulib/tests/compatibility/trunc/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/truncf/golden_subst.h.in gnulib/tests/compatibility/truncf/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/truncl/golden_subst.h.in gnulib/tests/compatibility/truncl/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/uchar_h/golden_subst.h.in gnulib/tests/compatibility/uchar_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/unlinkat/golden_subst.h.in gnulib/tests/compatibility/unlinkat/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/vfprintf-posix/golden_subst.h.in gnulib/tests/compatibility/vfprintf-posix/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/wchar_h/golden_subst.h.in gnulib/tests/compatibility/wchar_h/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/wcrtomb/golden_subst.h.in gnulib/tests/compatibility/wcrtomb/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/wcsrtombs/golden_subst.h.in gnulib/tests/compatibility/wcsrtombs/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/wctob/golden_subst.h.in gnulib/tests/compatibility/wctob/golden_subst_macos.h.in
git mv gnulib/tests/compatibility/wmempcpy/golden_subst.h.in gnulib/tests/compatibility/wmempcpy/golden_subst_macos.h.in
