/* gnulib_threadlib.h.in - AC_SUBST placeholders */
#define SUBST_LIBMULTITHREAD @LIBMULTITHREAD@
#define SUBST_LIBPMULTITHREAD @LIBPMULTITHREAD@
#define SUBST_LIBPTHREAD @LIBPTHREAD@
#define SUBST_LIBSTDTHREAD @LIBSTDTHREAD@
#define SUBST_LIBTHREAD @LIBTHREAD@
#define SUBST_LIB_SCHED_YIELD @LIB_SCHED_YIELD@
#define SUBST_LTLIBMULTITHREAD @LTLIBMULTITHREAD@
#define SUBST_LTLIBTHREAD @LTLIBTHREAD@
#define SUBST_SCHED_YIELD_LIB @SCHED_YIELD_LIB@
