"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/mbrtoc32.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks")

autoconf(
    name = "gl_FUNC_MBRTOC32",
    checks = [
        checks.AC_SUBST(
            "HAVE_MBRTOC32",
            condition = "gl_cv_func_mbrtoc32",
            if_false = 0,
            if_true = 1,
        ),
        checks.AC_SUBST(
            "REPLACE_MBRTOC32",
            condition = "gl_cv_func_mbrtoc32",
            if_false = 0,
            if_true = 1,
        ),
    ] + select({
        "@platforms//os:linux": [
            checks.AC_DEFINE("MBRTOC32_IN_C_LOCALE_MAYBE_EILSEQ", 1),
        ],
        "//conditions:default": [],
    }),
    visibility = ["//gnulib:__subpackages__"],
    deps = [
        ":gl_CHECK_FUNC_MBRTOC32",
        ":gl_MBRTOC32_C_LOCALE",
        ":gl_MBRTOC32_EMPTY_INPUT",
        ":gl_MBRTOC32_SANITYCHECK",
        ":gl_MBRTOC32_UTF8_LOCALE",
        "//autoconf/macros/AC_TYPE_MBSTATE_T",
        "//gnulib/m4/mbrtowc:gl_MBSTATE_T_BROKEN",
        "//gnulib/m4/uchar_h",
    ],
)

autoconf(
    name = "gl_CHECK_FUNC_MBRTOC32",
    checks = [
        checks.AC_CHECK_DECL(
            "mbrtoc32",
            includes = [
                "#ifdef __HAIKU__\n#include <stdint.h>\n#endif",
                "#include <uchar.h>",
            ],
        ),
        checks.AC_TRY_LINK(
            name = "gl_cv_func_mbrtoc32",
            code = """#include <stdlib.h>
#ifdef __HAIKU__
#include <stdint.h>
#endif
#include <uchar.h>
char32_t c;
int main(void) { return mbrtoc32(&c, "", 1, NULL) == 0; }""",
            requires = ["ac_cv_have_decl_mbrtoc32==1"],
        ),
    ],
    visibility = ["//gnulib:__subpackages__"],
)

autoconf(
    name = "gl_MBRTOC32_EMPTY_INPUT",
    visibility = ["//gnulib:__subpackages__"],
    deps = ["//autoconf/macros/AC_CANONICAL_HOST"],
)

autoconf(
    name = "gl_MBRTOC32_C_LOCALE",
    visibility = ["//gnulib:__subpackages__"],
    deps = ["//autoconf/macros/AC_CANONICAL_HOST"],
)

autoconf(
    name = "gl_MBRTOC32_UTF8_LOCALE",
    visibility = ["//gnulib:__subpackages__"],
    deps = [
        "//autoconf/macros/AC_CANONICAL_HOST",
        "//gnulib/m4/locale-en",
        "//gnulib/m4/locale-zh",
    ],
)

autoconf(
    name = "gl_MBRTOC32_SANITYCHECK",
    checks = [
        checks.AC_DEFINE(
            "HAVE_WORKING_MBRTOC32",
            requires = ["gl_cv_func_mbrtoc32==1"],
        ),
        checks.AC_SUBST(
            "HAVE_WORKING_MBRTOC32",
            condition = "gl_cv_func_mbrtoc32",
            if_false = 0,
            if_true = 1,
        ),
    ],
    visibility = ["//gnulib:__subpackages__"],
    deps = [
        ":gl_CHECK_FUNC_MBRTOC32",
        "//autoconf/macros/AC_CANONICAL_HOST",
        "//gnulib/m4/c32rtomb:gl_C32RTOMB_SANITYCHECK",
        "//gnulib/m4/locale-en",
        "//gnulib/m4/locale-fr",
        "//gnulib/m4/locale-ja",
        "//gnulib/m4/locale-zh",
        "//gnulib/m4/uchar_h",
    ],
)

autoconf(
    name = "gl_PREREQ_MBRTOC32",
    visibility = ["//gnulib:__subpackages__"],
)

autoconf(
    name = "mbrtoc32",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_CHECK_FUNC_MBRTOC32",
        ":gl_FUNC_MBRTOC32",
        ":gl_MBRTOC32_C_LOCALE",
        ":gl_MBRTOC32_EMPTY_INPUT",
        ":gl_MBRTOC32_SANITYCHECK",
        ":gl_MBRTOC32_UTF8_LOCALE",
        ":gl_PREREQ_MBRTOC32",
    ],
)
