/* gnulib_stdint.h.in - AC_SUBST placeholders */
#define SUBST_BITSIZEOF_ @BITSIZEOF_@
#define SUBST_HAVE_C99_STDINT_H 1
#define SUBST_HAVE_INTTYPES_H 1
#define SUBST_HAVE_SIGNED_ @HAVE_SIGNED_@
#define SUBST_HAVE_STDINT_H 1
#define SUBST_HAVE_SYS_BITYPES_H 0
#define SUBST_HAVE_SYS_INTTYPES_H 0
#define SUBST_HAVE_SYS_TYPES_H 1
#define SUBST_HAVE_WCHAR_H 1
