/* gnulib_termios_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_DECL_TCGETSID 1
#define SUBST_HAVE_TERMIOS_H 1
#define SUBST_SYS_IOCTL_H_DEFINES_STRUCT_WINSIZE 1
#define SUBST_TERMIOS_H_DEFINES_STRUCT_WINSIZE 1
