/* gnulib_pty_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_FORKPTY @HAVE_FORKPTY@
#define SUBST_HAVE_LIBUTIL_H 0
#define SUBST_HAVE_OPENPTY @HAVE_OPENPTY@
#define SUBST_HAVE_PTY_H 0
#define SUBST_HAVE_UTIL_H 1
#define SUBST_REPLACE_FORKPTY @REPLACE_FORKPTY@
#define SUBST_REPLACE_OPENPTY @REPLACE_OPENPTY@
