"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/tcgetsid.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks", "utils")

autoconf(
    name = "gl_FUNC_TCGETSID",
    checks = [
        # AC_CHECK_DECLS([tcgetsid], , , [[#include <termios.h>]])
        checks.AC_CHECK_DECL(
            "tcgetsid",
            name = "ac_cv_have_decl_tcgetsid",
            includes = ["#include <termios.h>"],
        ),
        checks.AC_DEFINE(
            "HAVE_DECL_TCGETSID",
            condition = "ac_cv_have_decl_tcgetsid",
            if_false = 0,
            if_true = 1,
        ),
        # if test $ac_cv_have_decl_tcgetsid = no; then HAVE_DECL_TCGETSID=0
        checks.AC_SUBST(
            "HAVE_DECL_TCGETSID",
            condition = "ac_cv_have_decl_tcgetsid",
            if_false = 0,
            if_true = 1,
        ),
        checks.AC_TRY_LINK(
            name = "gl_cv_func_tcgetsid",
            code = utils.AC_LANG_PROGRAM(
                ["#include <termios.h>"],
                "return tcgetsid(0);",
            ),
        ),
        checks.AC_SUBST(
            "HAVE_TCGETSID",
            condition = "gl_cv_func_tcgetsid",
            if_false = 0,
            if_true = 1,
        ),
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//autoconf/macros/AC_CHECK_INCLUDES_DEFAULT",
        "//gnulib/m4/extensions",  # AC_REQUIRE([AC_USE_SYSTEM_EXTENSIONS])
    ],
)

# gl_PREREQ_TCGETSID - lines 40-42 (empty)
autoconf(
    name = "gl_PREREQ_TCGETSID",
    checks = [],
    visibility = ["//visibility:public"],
)

autoconf(
    name = "tcgetsid",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_FUNC_TCGETSID",
        ":gl_PREREQ_TCGETSID",
    ],
)
