/* config.h.in - AC_DEFINE placeholders */
#define HAVE_SNPRINTF_RETVAL_C99 1
#define HAVE_SNPRINTF_TRUNCATION_C99 1
/* #undef HAVE_WORKING_SWPRINTF */
#define NEED_PRINTF_DIRECTIVE_A 1
/* #undef NEED_PRINTF_DIRECTIVE_B */
/* #undef NEED_PRINTF_DIRECTIVE_F */
/* #undef NEED_PRINTF_DIRECTIVE_LC */
/* #undef NEED_PRINTF_DIRECTIVE_LS */
/* #undef NEED_PRINTF_DIRECTIVE_UPPERCASE_B */
#define NEED_PRINTF_DOUBLE 1
#define NEED_PRINTF_ENOMEM 1
/* #undef NEED_PRINTF_FLAG_ALT_PRECISION_ZERO */
/* #undef NEED_PRINTF_FLAG_GROUPING */
/* #undef NEED_PRINTF_FLAG_GROUPING_INT */
/* #undef NEED_PRINTF_FLAG_LEFTADJUST */
/* #undef NEED_PRINTF_FLAG_ZERO */
/* #undef NEED_PRINTF_INFINITE_DOUBLE */
/* #undef NEED_PRINTF_INFINITE_LONG_DOUBLE */
#define NEED_PRINTF_LONG_DOUBLE 1
/* #undef NEED_PRINTF_UNBOUNDED_PRECISION */
/* #undef NEED_WPRINTF_DIRECTIVE_C */
/* #undef NEED_WPRINTF_DIRECTIVE_LA */
/* #undef NEED_WPRINTF_DIRECTIVE_LC */
/* #undef REPLACE_VASNPRINTF */
/* #undef SUPPORT_GNU_PRINTF_DIRECTIVES */
/* #undef ptrdiff_t */
