/* config.h.in - AC_DEFINE placeholders */
#define HAVE_SNPRINTF_RETVAL_C99 1
#define HAVE_SNPRINTF_TRUNCATION_C99 1
/* #undef HAVE_WORKING_SWPRINTF */
#define NEED_PRINTF_DIRECTIVE_A 1
#define NEED_PRINTF_DIRECTIVE_B 1
/* #undef NEED_PRINTF_DIRECTIVE_F */
/* #undef NEED_PRINTF_DIRECTIVE_LC */
/* #undef NEED_PRINTF_DIRECTIVE_LS */
#define NEED_PRINTF_DIRECTIVE_UPPERCASE_B 1
#define NEED_PRINTF_DOUBLE 1
#define NEED_PRINTF_ENOMEM 1
/* #undef NEED_PRINTF_FLAG_ALT_PRECISION_ZERO */
/* #undef NEED_PRINTF_FLAG_GROUPING */
#define NEED_PRINTF_FLAG_GROUPING_INT 1
/* #undef NEED_PRINTF_FLAG_LEFTADJUST */
/* #undef NEED_PRINTF_FLAG_ZERO */
/* #undef NEED_PRINTF_INFINITE_DOUBLE */
/* #undef NEED_PRINTF_INFINITE_LONG_DOUBLE */
#define NEED_PRINTF_LONG_DOUBLE 1
/* #undef NEED_PRINTF_UNBOUNDED_PRECISION */
#define NEED_WPRINTF_DIRECTIVE_C 1
/* #undef NEED_WPRINTF_DIRECTIVE_LA */
#define NEED_WPRINTF_DIRECTIVE_LC 1
/* #undef REPLACE_VASNPRINTF */
#define SUPPORT_GNU_PRINTF_DIRECTIVES 1
/* #undef ptrdiff_t */
