/* gnulib_langinfo_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_LANGINFO_ABALTMON @HAVE_LANGINFO_ABALTMON@
#define SUBST_HAVE_LANGINFO_ALTMON @HAVE_LANGINFO_ALTMON@
#define SUBST_HAVE_LANGINFO_CODESET @HAVE_LANGINFO_CODESET@
#define SUBST_HAVE_LANGINFO_ERA @HAVE_LANGINFO_ERA@
#define SUBST_HAVE_LANGINFO_H 1
#define SUBST_HAVE_NL_LANGINFO 1
#define SUBST_REPLACE_NL_LANGINFO 0
