"""Pinned GNU autotools used as the conformance oracle.

Neither autoconf nor automake compiles anything.  Their `make install` is a
`sed` over a handful of `*.in` templates, so the whole install happens at
fetch time inside a repository rule and no build action is required.

Every location the tools would normally have baked in at install time is
overridable through their own environment variables (`autom4te_perllibdir`,
`AC_MACRODIR`, `AUTOM4TE_CFG`, `AUTOM4TE`, `trailer_m4`, `M4`,
`AUTOMAKE_UNINSTALLED`, `AUTOMAKE_LIBDIR`) or command line options
(`--automake-acdir`, `--system-acdir`).  The tester sets all of them from
runfiles, so the templates below are filled with sentinel paths that fail
loudly if anything ever falls back to them.
"""

AUTOCONF_VERSION = "2.73"
AUTOCONF_RELEASE_YEAR = "2026"
_AUTOCONF_INTEGRITY = "sha256-n9ZyschCX6wvpn+gR3uZCYcmi5D/NtXwFtrle+DWtS4="

AUTOMAKE_VERSION = "1.18.1"
AUTOMAKE_API_VERSION = "1.18"
AUTOMAKE_RELEASE_YEAR = "2025"
_AUTOMAKE_INTEGRITY = "sha256-FoqjYyeDUbia9WaERI9SWlvOUHnQtoQr2RD90/FkaIc="

# Anything that falls through to an install-time default is a bug in the
# runtime environment setup; make it fail with an obvious path.
_SENTINEL = "/nonexistent/rules_cc_autoconf-autotools"

def _gnu_urls(package, filename):
    return [
        "https://mirrors.kernel.org/gnu/{}/{}".format(package, filename),
        "https://ftpmirror.gnu.org/gnu/{}/{}".format(package, filename),
        "https://ftp.gnu.org/gnu/{}/{}".format(package, filename),
        "https://mirror.bazel.build/ftp.gnu.org/gnu/{}/{}".format(package, filename),
    ]

def _substitute(ctx, output, template, substitutions, executable = False):
    content = ctx.read(template)
    for key, value in substitutions.items():
        content = content.replace(key, value)
    ctx.file(output, content, executable = executable)

_AUTOCONF_BUILD = """\
# Generated by rules_cc_autoconf//autoconf/tests/gnu:deps.bzl
package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/*", "lib/**"]))

filegroup(
    name = "files",
    srcs = glob(
        ["bin/*", "lib/**"],
        exclude = ["lib/**/*.in"],
    ) + ["lib/autom4te.in"],
)
"""

def _autoconf_repository_impl(ctx):
    filename = "autoconf-{}.tar.xz".format(ctx.attr.version)
    ctx.download_and_extract(
        url = _gnu_urls("autoconf", filename),
        integrity = ctx.attr.integrity,
        stripPrefix = "autoconf-{}".format(ctx.attr.version),
    )

    # Mirrors the `edit` rule in autoconf's Makefile.am.
    edit = {
        "@AWK@": "awk",
        "@M4@": "m4",
        "@M4_DEBUGFILE@": "--debugfile",
        "@M4_GNU@": "--gnu",
        "@PACKAGE_NAME@": "GNU Autoconf",
        "@PERL@": "/usr/bin/env perl",
        "@PERL_FLOCK@": "yes",
        "@RELEASE_YEAR@": ctx.attr.release_year,
        "@SHELL@": "/bin/sh",
        "@VERSION@": ctx.attr.version,
        "@autoconf-name@": "autoconf",
        "@autoheader-name@": "autoheader",
        "@autom4te-name@": "autom4te",
        "@bindir@": _SENTINEL + "/bin",
        "@configure_input@": "Generated by rules_cc_autoconf from {}.in".format("bin/SCRIPT"),
        "@pkgdatadir@": _SENTINEL + "/share/autoconf",
        "@prefix@": _SENTINEL,
    }
    for script in ["autoconf", "autom4te", "autoheader", "autoreconf", "autoupdate", "ifnames", "autoscan"]:
        _substitute(ctx, "bin/" + script, "bin/{}.in".format(script), edit, executable = True)

    # `lib/autoconf_version.m4` is normally produced by config.status.
    _substitute(ctx, "lib/autoconf_version.m4", "lib/autoconf_version.in", {
        "@PACKAGE_BUGREPORT@": "bug-autoconf@gnu.org",
        "@PACKAGE_NAME@": "GNU Autoconf",
        "@PACKAGE_STRING@": "GNU Autoconf {}".format(ctx.attr.version),
        "@PACKAGE_TARNAME@": "autoconf",
        "@PACKAGE_URL@": "https://www.gnu.org/software/autoconf/",
        "@PACKAGE_VERSION@": ctx.attr.version,
        "@RELEASE_YEAR@": ctx.attr.release_year,
        "@configure_input@": "Generated by rules_cc_autoconf from lib/autoconf_version.in",
    })

    # `lib/autom4te.cfg` needs an absolute `--prepend-include`; the tester
    # renders it from `lib/autom4te.in` at run time.  Frozen `*.m4f` files are
    # optional: autom4te falls back to the `*.m4` sources when they are absent.

    ctx.file("BUILD.bazel", _AUTOCONF_BUILD)

autoconf_repository = repository_rule(
    doc = "Fetches and installs GNU autoconf without a build step.",
    implementation = _autoconf_repository_impl,
    attrs = {
        "integrity": attr.string(mandatory = True),
        "release_year": attr.string(mandatory = True),
        "version": attr.string(mandatory = True),
    },
)

_AUTOMAKE_BUILD = """\
# Generated by rules_cc_autoconf//autoconf/tests/gnu:deps.bzl
package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/*", "lib/Automake/*.pm", "m4/**"]))

filegroup(
    name = "files",
    srcs = ["bin/aclocal"] + glob([
        "lib/Automake/*.pm",
        "m4/*.m4",
        "m4/internal/*.m4",
    ]),
)
"""

def _automake_repository_impl(ctx):
    filename = "automake-{}.tar.xz".format(ctx.attr.version)
    ctx.download_and_extract(
        url = _gnu_urls("automake", filename),
        integrity = ctx.attr.integrity,
        stripPrefix = "automake-{}".format(ctx.attr.version),
    )

    # Mirrors the `do_subst` rule in automake's Makefile.am.
    do_subst = {
        "@APIVERSION@": ctx.attr.api_version,
        "@PACKAGE@": "automake",
        "@PACKAGE_BUGREPORT@": "bug-automake@gnu.org",
        "@PACKAGE_URL@": "https://www.gnu.org/software/automake/",
        "@PERL@": "/usr/bin/env perl",
        "@RELEASE_YEAR@": ctx.attr.release_year,
        "@VERSION@": ctx.attr.version,
        "@am_AUTOM4TE@": "autom4te",
        "@configure_input@": "Generated by rules_cc_autoconf",
        "@datadir@": _SENTINEL + "/share",
    }
    _substitute(ctx, "bin/aclocal", "bin/aclocal.in", do_subst, executable = True)
    _substitute(ctx, "lib/Automake/Config.pm", "lib/Automake/Config.in", do_subst)
    _substitute(ctx, "m4/amversion.m4", "m4/amversion.in", do_subst)

    ctx.file("BUILD.bazel", _AUTOMAKE_BUILD)

automake_repository = repository_rule(
    doc = "Fetches and installs GNU automake's `aclocal` without a build step.",
    implementation = _automake_repository_impl,
    attrs = {
        "api_version": attr.string(mandatory = True),
        "integrity": attr.string(mandatory = True),
        "release_year": attr.string(mandatory = True),
        "version": attr.string(mandatory = True),
    },
)

def _autotools_impl(module_ctx):
    autoconf_repository(
        name = "autoconf",
        version = AUTOCONF_VERSION,
        release_year = AUTOCONF_RELEASE_YEAR,
        integrity = _AUTOCONF_INTEGRITY,
    )
    automake_repository(
        name = "automake",
        version = AUTOMAKE_VERSION,
        api_version = AUTOMAKE_API_VERSION,
        release_year = AUTOMAKE_RELEASE_YEAR,
        integrity = _AUTOMAKE_INTEGRITY,
    )

    return module_ctx.extension_metadata(
        reproducible = True,
        root_module_direct_deps = [],
        root_module_direct_dev_deps = ["autoconf", "automake"],
    )

autotools = module_extension(
    doc = "Pinned GNU autoconf and automake sources for the conformance oracle.",
    implementation = _autotools_impl,
)
