"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/c-nstrftime.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks")

autoconf(
    name = "gl_C_GNU_STRFTIME",
    checks = [
        # gl_CHECK_FUNCS_ANDROID([strftime_l], [[#include <time.h>]]):
        # a link test; HAVE_STRFTIME_L is only defined when the function exists.
        checks.AC_CHECK_FUNC(
            "strftime_l",
            define = "HAVE_STRFTIME_L",
        ),
        # AC_CHECK_FUNCS_ONCE([strftime_lz])
        checks.AC_CHECK_FUNC(
            "strftime_lz",
            define = "HAVE_STRFTIME_LZ",
        ),
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//gnulib/m4/tm_gmtoff",  # AC_REQUIRE([gl_TM_GMTOFF])
        # Note: AC_REQUIRE([AC_C_RESTRICT]) is a standard autoconf macro
    ],
)

autoconf(
    name = "c-nstrftime",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_C_GNU_STRFTIME",
    ],
)
