/* gnulib_monetary_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_MONETARY_H 1
#define SUBST_HAVE_STRFMON_L @HAVE_STRFMON_L@
#define SUBST_HAVE_XLOCALE_H 1
#define SUBST_REPLACE_STRFMON_L @REPLACE_STRFMON_L@
