/* gnulib_strings_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_DECL_STRNCASECMP @HAVE_DECL_STRNCASECMP@
#define SUBST_HAVE_FFS 1
#define SUBST_HAVE_STRCASECMP 1
#define SUBST_HAVE_STRCASECMP_L @HAVE_STRCASECMP_L@
#define SUBST_HAVE_STRINGS_H 1
#define SUBST_HAVE_STRNCASECMP 1
#define SUBST_HAVE_STRNCASECMP_L @HAVE_STRNCASECMP_L@
#define SUBST_REPLACE_STRCASECMP @REPLACE_STRCASECMP@
#define SUBST_REPLACE_STRCASECMP_L @REPLACE_STRCASECMP_L@
#define SUBST_REPLACE_STRNCASECMP @REPLACE_STRNCASECMP@
#define SUBST_REPLACE_STRNCASECMP_L @REPLACE_STRNCASECMP_L@
