/* gnulib_netdb_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_DECL_FREEADDRINFO 1
#define SUBST_HAVE_DECL_GAI_STRERROR 1
#define SUBST_HAVE_DECL_GETADDRINFO 1
#define SUBST_HAVE_DECL_GETNAMEINFO 1
#define SUBST_HAVE_NETDB_H 1
#define SUBST_HAVE_STRUCT_ADDRINFO 1
#define SUBST_REPLACE_GAI_STRERROR 0
#define SUBST_REPLACE_GETADDRINFO 0
