/* gnulib_arpa_inet_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_ARPA_INET_H 1
#define SUBST_HAVE_DECL_HTONL 1
#define SUBST_HAVE_DECL_HTONS 1
#define SUBST_HAVE_DECL_INET_NTOP 1
#define SUBST_HAVE_DECL_INET_PTON 1
#define SUBST_HAVE_DECL_NTOHL 1
#define SUBST_HAVE_DECL_NTOHS 1
#define SUBST_REPLACE_INET_NTOP 0
#define SUBST_REPLACE_INET_PTON 0
