"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/stddef_h.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks", "utils")
load("//gnulib:macros.bzl", gl_macros = "macros")

# gl_STDDEF_H - lines 11-124
autoconf(
    name = "gl_STDDEF_H",
    checks = [
        checks.AC_TRY_COMPILE(
            name = "gl_cv_type_max_align_t",
            code = utils.AC_LANG_PROGRAM(
                ["""
/* On FreeBSD 12.0/x86, max_align_t defined by <stddef.h> has
   the correct alignment with the default (wrong) definition of
   _Alignof, but a wrong alignment as soon as we activate an
   ISO C compliant _Alignof definition.  */
#if ((defined __GNUC__ && 4 <= __GNUC__) || defined __clang__) && !defined __cplusplus
#define _Alignof(type) __builtin_offsetof (struct { char __a; type __b; }, __b)
#endif
#include <stddef.h>
unsigned int s = sizeof (max_align_t);
#if defined __GNUC__ || defined __clang__ || defined __IBM__ALIGNOF__
int check1[2 * (__alignof__ (double) <= __alignof__ (max_align_t)) - 1];
int check2[2 * (__alignof__ (long double) <= __alignof__ (max_align_t)) - 1];
#endif
typedef struct { char a; max_align_t b; } max_helper;
typedef struct { char a; long b; } long_helper;
typedef struct { char a; double b; } double_helper;
typedef struct { char a; long double b; } long_double_helper;
int check3[2 * (offsetof (long_helper, b) <= offsetof (max_helper, b)) - 1];
int check4[2 * (offsetof (double_helper, b) <= offsetof (max_helper, b)) - 1];
int check5[2 * (offsetof (long_double_helper, b) <= offsetof (max_helper, b)) - 1];
"""],
                "",
            ),
        ),
        checks.AC_SUBST(
            "HAVE_MAX_ALIGN_T",
            condition = "gl_cv_type_max_align_t",
            if_false = 0,
            if_true = 1,
        ),
        checks.AC_TRY_COMPILE(
            name = "gl_cv_decl_null_works",
            code = utils.AC_LANG_PROGRAM(
                ["""
#include <stddef.h>
int test[2 * (sizeof NULL == sizeof (void *)) - 1];
"""],
                "",
            ),
        ),
        checks.AC_SUBST(
            "REPLACE_NULL",
            condition = "gl_cv_decl_null_works",
            if_false = 1,
            if_true = 0,
        ),
        checks.AC_TRY_LINK(
            name = "gl_cv_c_func_unreachable",
            code = utils.AC_LANG_PROGRAM(
                ["#include <stddef.h>"],
                "unreachable();",
            ),
            language = "c",
        ),
        checks.AC_SUBST(
            "HAVE_C_UNREACHABLE",
            condition = "gl_cv_c_func_unreachable",
            if_false = 0,
            if_true = 1,
        ),
        # Upstream provides gl_unreachable() unconditionally.
        checks.M4_VARIABLE("GL_GENERATE_STDDEF_H", "true"),
        checks.AC_TRY_COMPILE(
            name = "gl_cv_nullptr_t_needs_stddef",
            code = utils.AC_LANG_PROGRAM(
                ["nullptr_t x;"],
                "",
            ),
        ),
        checks.AC_SUBST(
            "NULLPTR_T_NEEDS_STDDEF",
            condition = "gl_cv_nullptr_t_needs_stddef",
            if_false = 1,
            if_true = 0,
        ),
        checks.AC_TRY_COMPILE(
            name = "gl_cv_stddef_idempotent",
            code = utils.AC_LANG_PROGRAM(
                ["""
#if ((__GNUC__ == 13 && __GNUC_MINOR__ <= 3) || (__GNUC__ == 14 && __GNUC_MINOR__ <= 2))
# error "bug 114870 is present"
#endif
"""],
                "",
            ),
        ),
        checks.AC_SUBST(
            "STDDEF_NOT_IDEMPOTENT",
            condition = "gl_cv_stddef_idempotent",
            if_false = 1,
            if_true = 0,
        ),
    ] + gl_macros.GL_NEXT_HEADERS(["stddef.h"]),
    visibility = ["//visibility:public"],
    deps = [
        "//gnulib/m4/extensions",
        "//gnulib/m4/include_next",
    ],
)

# gl_STDDEF_MODULE_INDICATOR - lines 126-135
autoconf(
    name = "gl_STDDEF_MODULE_INDICATOR",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_STDDEF_H_REQUIRE_DEFAULTS",
    ],
)

# gl_STDDEF_H_REQUIRE_DEFAULTS - lines 137-146
autoconf(
    name = "gl_STDDEF_H_REQUIRE_DEFAULTS",
    visibility = ["//visibility:private"],
    deps = [
        ":gl_STDDEF_H_DEFAULTS",
    ],
)

# gl_STDDEF_H_DEFAULTS - lines 148-155
autoconf(
    name = "gl_STDDEF_H_DEFAULTS",
    checks = [
        checks.AC_SUBST("NULLPTR_T_NEEDS_STDDEF", 1),
        checks.AC_SUBST("STDDEF_NOT_IDEMPOTENT", 0),
        checks.AC_SUBST("REPLACE_NULL", 0),
        checks.AC_SUBST("HAVE_MAX_ALIGN_T", 1),
    ],
    visibility = ["//visibility:private"],
)

autoconf(
    name = "stddef_h",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_STDDEF_H",
    ],
)

autoconf(
    name = "defaults",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_STDDEF_H_REQUIRE_DEFAULTS",
    ],
)
