"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/mbsinit.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks")

# gl_FUNC_MBSINIT - lines 9-41
autoconf(
    name = "gl_FUNC_MBSINIT",
    checks = [
        checks.AC_CHECK_FUNC(
            "mbsinit",
            define = "HAVE_MBSINIT",
            subst = True,
        ),
        checks.AC_CHECK_DECL(
            "mbsinit",
            define = "HAVE_DECL_MBSINIT",
            includes = ["#include <wchar.h>"],
            requires = ["!ac_cv_func_mbsinit"],
        ),
    ] + select({
        "@platforms//os:windows": [
            checks.AC_SUBST(
                "REPLACE_MBSINIT",
                condition = "ac_cv_func_mbsinit || ac_cv_have_decl_mbsinit",
                if_false = 0,
                if_true = 1,
            ),
        ],
        "//conditions:default": [
            checks.AC_SUBST(
                "REPLACE_MBSINIT",
                condition = "(!ac_cv_func_mbsinit && ac_cv_have_decl_mbsinit) || (ac_cv_func_mbsinit && REPLACE_MBSTATE_T==1)",
                if_false = 0,
                if_true = 1,
            ),
        ],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//autoconf/macros/AC_CANONICAL_HOST",
        "//autoconf/macros/AC_TYPE_MBSTATE_T",
        "//gnulib/m4/mbrtowc:gl_MBSTATE_T_BROKEN",
    ],
)

# gl_PREREQ_MBSINIT - lines 43-46
autoconf(
    name = "gl_PREREQ_MBSINIT",
    visibility = ["//visibility:public"],
)

autoconf(
    name = "mbsinit",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_FUNC_MBSINIT",
        ":gl_PREREQ_MBSINIT",
    ],
)
