/* gnulib_ctype_h.h.in - AC_SUBST placeholders */
#define SUBST_HAVE_ISALNUM_L 1
#define SUBST_HAVE_ISALPHA_L 1
#define SUBST_HAVE_ISBLANK 1
#define SUBST_HAVE_ISBLANK_L 1
#define SUBST_HAVE_ISCNTRL_L 1
#define SUBST_HAVE_ISDIGIT_L 1
#define SUBST_HAVE_ISGRAPH_L 1
#define SUBST_HAVE_ISLOWER_L 1
#define SUBST_HAVE_ISPRINT_L 1
#define SUBST_HAVE_ISPUNCT_L 1
#define SUBST_HAVE_ISSPACE_L 1
#define SUBST_HAVE_ISUPPER_L 1
#define SUBST_HAVE_ISXDIGIT_L 1
#define SUBST_HAVE_TOLOWER_L 1
#define SUBST_HAVE_TOUPPER_L 1
