"""https://github.com/coreutils/gnulib/blob/1039a5f2cee3cda1c11f64a5eb3a15b2e87cd2f0/m4/execvpe.m4"""

load("//autoconf:autoconf_toolchain.bzl", autoconf = "autoconf_cache")
load("//autoconf:checks.bzl", "checks")
load("//gnulib:macros.bzl", gl_macros = "macros")

# gl_FUNC_EXECVPE: Check for execvpe; set HAVE_EXECVPE and REPLACE_EXECVPE.
autoconf(
    name = "gl_FUNC_EXECVPE",
    checks = select({
        # case "$host_os" in
        #   mingw* | windows*) REPLACE_EXECVPE=1 ;;
        # (no function check at all: HAVE_EXECVPE stays undefined / 1)
        "@platforms//os:windows": [
            checks.AC_SUBST("REPLACE_EXECVPE", "1"),
        ],
        #   *)
        #     gl_CHECK_FUNCS_ANDROID([execvpe], [[#include <unistd.h>]])
        #     if test $ac_cv_func_execvpe != yes; then
        #       HAVE_EXECVPE=0
        #       ...
        "//conditions:default": gl_macros.GL_CHECK_FUNCS_ANDROID(
            ["execvpe"],
            includes = ["#include <unistd.h>"],
        ) + [
            checks.AC_SUBST(
                "HAVE_EXECVPE",
                condition = "ac_cv_func_execvpe",
                if_false = "0",
                if_true = "1",
            ),
            checks.AC_SUBST("REPLACE_EXECVPE", "0"),
        ],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//autoconf/macros/AC_CANONICAL_HOST",
        "//autoconf/macros/AC_CHECK_INCLUDES_DEFAULT",
        "//gnulib/m4/extensions",
    ],
)

autoconf(
    name = "execvpe",
    visibility = ["//visibility:public"],
    deps = [
        ":gl_FUNC_EXECVPE",
    ],
)
