/* gnulib_stdbit_h.h.in - AC_SUBST placeholders */
#define SUBST_GL_STDC_BIT_CEIL @GL_STDC_BIT_CEIL@
#define SUBST_GL_STDC_BIT_FLOOR @GL_STDC_BIT_FLOOR@
#define SUBST_GL_STDC_BIT_WIDTH @GL_STDC_BIT_WIDTH@
#define SUBST_GL_STDC_COUNT_ONES @GL_STDC_COUNT_ONES@
#define SUBST_GL_STDC_COUNT_ZEROS @GL_STDC_COUNT_ZEROS@
#define SUBST_GL_STDC_FIRST_LEADING_ONE @GL_STDC_FIRST_LEADING_ONE@
#define SUBST_GL_STDC_FIRST_LEADING_ZERO @GL_STDC_FIRST_LEADING_ZERO@
#define SUBST_GL_STDC_FIRST_TRAILING_ONE @GL_STDC_FIRST_TRAILING_ONE@
#define SUBST_GL_STDC_FIRST_TRAILING_ZERO @GL_STDC_FIRST_TRAILING_ZERO@
#define SUBST_GL_STDC_HAS_SINGLE_BIT @GL_STDC_HAS_SINGLE_BIT@
#define SUBST_GL_STDC_LEADING_ONES @GL_STDC_LEADING_ONES@
#define SUBST_GL_STDC_LEADING_ZEROS @GL_STDC_LEADING_ZEROS@
#define SUBST_GL_STDC_TRAILING_ONES @GL_STDC_TRAILING_ONES@
#define SUBST_GL_STDC_TRAILING_ZEROS @GL_STDC_TRAILING_ZEROS@
