name: Docs

on:
  push:
    branches:
      - main

env:
  BAZEL_STARTUP_FLAGS: --bazelrc=${{ github.workspace }}/.github/github.bazelrc

jobs:
  docs:
    name: Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/buildbuddy
        with:
          api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
          user: "Docs"
      - name: Run tests
        run: bazel ${BAZEL_STARTUP_FLAGS[@]} run --compilation_mode=opt --stamp //docs:publish_book
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/book # The folder the action should deploy.
